"""add friends table

Revision ID: d957492f433d
Revises: f382cb809ce0
Create Date: 2023-09-28 21:42:41.281957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd957492f433d'
down_revision: Union[str, None] = 'f382cb809ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_friends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_friend', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_friend'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_friends_id'), 'user_friends', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_friends_id'), table_name='user_friends')
    op.drop_table('user_friends')
    # ### end Alembic commands ###
