"""empty message

Revision ID: deee3b4d9bb7
Revises: d957492f433d
Create Date: 2023-09-29 15:25:06.813851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deee3b4d9bb7'
down_revision: Union[str, None] = 'd957492f433d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_friends', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_friends', sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
